# Copyright (C) 2024 8 Hobbies, LLC <hong@8hobbies.com>
#
# Permission to use, copy, modify, and/or distribute this software for anypurpose with or without fee
# is hereby granted.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIESWITH REGARD TO THIS SOFTWARE
# INCLUDING ALL IMPLIED WARRANTIES OFMERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE
# LIABLE FORANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGESWHATSOEVER RESULTING
# FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN ANACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS
# ACTION, ARISING OUT OFOR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# OR
#
# This work is marked with CC0 1.0 Universal.
# Visit https://creativecommons.org/publicdomain/zero/1.0/legalcode.txt for the full text of the license.

name: Build and Deploy Pages

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-24.04
    container: hugomods/hugo:reg-git-0.128.2
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build the site
        working-directory: website
        run: ./build-website.sh

      - name: Install tar
        run: apk add tar

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: website/public

  deploy:
    name: Deploy Pages
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: [build]
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
